---
- name: Install ruby
  apt:
    name: ruby
    state: present
    update_cache: yes

- name: Copy pdumpfs script
  copy:
    src: pdumpfs
    dest: /usr/local/bin/
    mode: 0755
- name: Copy pdumpfs-clean script
  copy:
    src: pdumpfs-clean
    dest: /usr/local/bin/
    mode: 0755
- name: Copy backup.sh script
  copy:
    src: backup.sh
    dest: /usr/local/bin/
    mode: 0755

- name: regist pdumpfs to cron
  cron:
    name: backup with pdumpfs
    minute: "0"
    hour: "0"
    job: "/usr/local/bin/backup.sh"
